# Generated by Django 3.1.7 on 2021-05-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20210513_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='boost',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
