# Generated by Django 3.1.7 on 2021-06-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_boost_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boost',
            old_name='mainCycle',
            new_name='main_cycle',
        ),
        migrations.RenameField(
            model_name='maincycle',
            old_name='coinsCount',
            new_name='auto_click_power',
        ),
        migrations.RenameField(
            model_name='maincycle',
            old_name='clickPower',
            new_name='click_power',
        ),
        migrations.AddField(
            model_name='boost',
            name='boost_type',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='maincycle',
            name='coins_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maincycle',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
