# Generated by Django 3.1.7 on 2021-06-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20210608_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boost',
            old_name='main_cycle',
            new_name='mainCycle',
        ),
        migrations.RenameField(
            model_name='maincycle',
            old_name='auto_click_power',
            new_name='autoClickPower',
        ),
        migrations.RenameField(
            model_name='maincycle',
            old_name='click_power',
            new_name='clickPower',
        ),
        migrations.RenameField(
            model_name='maincycle',
            old_name='coins_count',
            new_name='coinsCount',
        ),
        migrations.AlterField(
            model_name='boost',
            name='level',
            field=models.IntegerField(),
        ),
    ]
